root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = ["-l 0", "convert", "-i internal/converter/testdata/002_text_page/index.html", "-o tmp/out.pdf"]
  bin = "./web2paper"
  cmd = "go build -buildvcs=false"
  delay = 100
  exclude_dir = [
    "assets",
    "tmp",
    "vendor",
    "testdata",
    ".git",
    "test-results",
  ]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = true
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = [
    "go",
    "html",
  ]
  include_file = []
  kill_delay = "0s"
  log = "tmp/build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = true
  silent = false
  time = false

[misc]
  clean_on_exit = false

[proxy]
  enabled = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
